app/laptops/forms.py
# Imports to handle form processing
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, DecimalField, SelectField, RadioField, HiddenField
from wtforms.validators import DataRequired, Length, NumberRange

'''
    NOTE: This is where all WT Forms classes will be defined for this module
'''

# Form definition for adding a laptop to the database
class AddLaptopForm(FlaskForm):
    brand = StringField('Brand:', validators=[DataRequired(message="Enter a brand (e.g. Dell, Apple)"), Length(max=50)])
    
    model = StringField('Model:', validators=[Length(max=255) ])
    
    price = DecimalField('Price:', validators=[DataRequired(message="Enter the purchase price.")
                , NumberRange(min=0.01,  message="Price must be greater than $0")])
    
    ram_memory = IntegerField('RAM (GB):', validators=[DataRequired(message="Amount of RAM is required")
                , NumberRange(min=2, max=128, message="Enter memory amount between 2 and 128")])
    
    rating = IntegerField('Ratung:', validators=[DataRequired(message="Rating on scale of 1 to 100")
                , NumberRange(min=2, max=128, message="Enter memory amount between 1 and 100")])
    touch_screen = RadioField('Touch Screen:', choices=[ (0,"No"), (1,"Yes") ], validators=[DataRequired()])
    processor_id = SelectField('Processor:', validators=[DataRequired()])
    submit = SubmitField('Add Laptop')

app/laptops/__init__.py
from flask import Blueprint

laptops = Blueprint('laptops', __name__, template_folder='templates')

from . import routes, forms

app/laptops/routes.py
'''
This file will setup the routes (URLs) for each of the reports.
The actual report code will be in classes in separate files.
'''
from flask import render_template, redirect, url_for, flash

from . import laptops
from app.models.laptop import Laptop
from app.extensions import Base, engine, session

from flask_login import login_required


from . import AddLaptop
from .forms import AddLaptopForm


# Route for the laptop listing
@laptops.route('/laptops')
def laptop_listing():

    Base.metadata.create_all(engine)

    results = session.query(Laptop).all()
    # for laptop in results:
    #     print(f"ID: {laptop.processor.processor_id} Model: {laptop.processor.processor_name}")

    return render_template('laptops/listing.html', laptops = results)


# Route for adding a laptop to the database
@laptops.route('/laptops/add', methods=['GET', 'POST'])
@login_required
def laptopAdd():

    al = AddLaptop.AddLaptop()
    processors = al.buildProcessorList()

    # Create the Add Laptop Form
    form = AddLaptopForm()
    form.processor_id.choices = processors

    if form.validate_on_submit():

        print('We are adding a laptop here!!!!!')
        
        id = al.laptop_add(form)
        print(f'New id: {id}')
        
        url = '/laptops'
        return redirect(url, 302)

    return render_template('laptops/addlaptop.html', form=form)



app/laptops/templates/laptops/addlaptop.html
{% extends "layout/base.html" %}

{% block title %}Add Laptop{% endblock %}

{% block body %}
<h1 class="is-size-3">Add Laptop</h1>

<div class="columns">
    <div class="column is-half">
        <form action="{{ url_for('laptops.laptopAdd') }}" method="POST">
            {{ form.hidden_tag() }}

            <div class="field">
                <label>{{ form.brand.label(class="label")}}</label>
                <div class="control">
                {{ form.brand(class="input is-info") }}
                </div>
            </div>

            <div class="field">
                <label>{{ form.model.label(class="label")}}</label>
                <div class="control">
                    {{ form.model(class="input is-info") }}
                </div>
            </div>

            <div class="field">
                <label>{{ form.processor_id.label(class="label")}}</label>
                <div class="control">
                    {{ form.processor_id(class="select is-info") }}
                </div>
            </div>

            <div class="field">
                <label>{{ form.price.label(class="label")}}</label>
                <div class="control">
                    {{ form.price(class="input is-info") }}
                </div>
            </div>

            <div class="field">
                <label>{{ form.rating.label(class="label")}}</label>
                <div class="control">
                    {{ form.rating(class="input is-info") }}
                </div>
            </div>

            <div class="field">
                <label>{{ form.ram_memory.label(class="label")}}</label>
                <div class="control">
                    {{ form.ram_memory(class="input is-info") }}
                </div>

            <div class="field">
                <div class="control">
                    <label class="label-inline">{{ form.touch_screen.label()}}
                        {{ form.touch_screen(class="radio") }}
                    </label>
                </div>
            </div>

            <div class="control">
                {{ form.submit(class="button is-success") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/laptops/templates/laptops/listing.html
{% extends "layout/base.html" %}

{% block title %}Laptop Ratings {% endblock %}


{% block body %}
<h1 class="title is-3">Laptop List</h1>

<div class="columns">
    <div class="column is-full">
        <table class="table table-striped table-hover">
            <thead>
                <th>Brand</th>
                <th>Model</th>
                <th>Processor</th>
                <th>RAM</th>
                <th>Touch</th>
                <th>Rating</th>
                <th>Price</th>
            </thead>
            <tbody>
                {% for laptop in laptops %}
                <tr>
                    <td>{{ laptop.brand }}</td>
                    <td>{{ laptop.model }}</td>
                    <td>{{ laptop.processor.processor_brand }} {{ laptop.processor.processor_name }}</td>
                    <td>{{ laptop.ram_memory }}</td>
                    <td>{{ laptop.touch_screen }}</td>
                    <td>{{ laptop.rating }}</td>
                    <td>{{ laptop.price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

{% endblock %}